version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: employee_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ems-backend:latest
    container_name: employee_backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads
    restart: always
    # No ports exposed! The backend is protected inside the bridge.

  frontend:
    image: ems-frontend:latest
    container_name: employee_frontend
    ports:
      - "3000:80"  # Unified Port (Moved to 3000 to avoid conflicts)
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  uploads_data:
