services:
  db:
    image: postgres:15-alpine
    container_name: employee_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: employee_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
    # In production, we don't need --reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    container_name: employee_frontend
    ports:
      - "80:80" # Maps port 80 inside container (Nginx) to 80 outside (Standard HTTP)
    depends_on:
      - backend

volumes:
  postgres_data:
  uploads_data:
